sudo: false
language: python
python:
  - "2.7"
# command to install wxPython using apt
# before_install:
#   - sudo apt-get update -qq
#   - sudo apt-get install -qq python-wxgtk2.8
# command to install other dependencies

addons:
  apt:
    packages:
      # for wxPython:
      - python-wxgtk2.8
      - python-wxtools
      - wx2.8-doc
      - wx2.8-examples
      - wx2.8-headers
      - wx2.8-i18n

install:
  - pip install -r requirements.txt --use-mirrors
  - python setup.py -q install
  - pip install codecov
  - pip install nose-cov

# command to run tests
script: nosetests --with-cov

# database setup
before_script:
  - mysql -e 'create database myapp_test;'
  - psql -c 'create database testdb;' -U postgres

after_success:
  - codecov

notifications:
  slack:
    secure: h18p9TjI6fiQ/8IT4lk9zcgC15z5HlK0UAYiegvf8ckpw3DadOZ2bo4YyeoAv6OJgp8JGYdw0C3UISfKpoiECdjJvuClk9ZFu5/i+J+3pTaedUbaxU+ps5hDfH5ubaRGLIro61Iz2bUfwqHftc5sxKhdfoEV1TI72gTs041I5I4=
