sudo: false
language: python
python:
  - "2.7"
  - "3.5"
addons:
  postgresql: "9.4"
  apt:
    sources:
      - travis-ci/sqlite3
    packages:
      - sqlite3

services:
  - postgresql
install:
  - pip install -r requirements.txt
  - python setup.py -q install
  - pip install codecov
  - pip install pytest-cov
  - pip install pytest-xdist


# command to run tests using py.test

script:
  - py.test -v --cov=retriever

# database setup
before_script:
  - sqlite3 --version
  - mysql -e 'create database myapp_test;'
  - psql -c 'create database testdb;' -U postgres

after_success:
  - codecov
  - retriever  install postgres FrayJorge -u postgres -d testdb
  - retriever  install postgres EltonTraits -u postgres -d testdb
  - retriever  install postgres Palmer2007 -u postgres -d testdb
  - retriever  install mysql gwdd -u travis
  - retriever  install mysql EltonTraits -u travis
  - retriever  install mysql leaf_herbivory -u travis

notifications:
  slack:
    secure: h18p9TjI6fiQ/8IT4lk9zcgC15z5HlK0UAYiegvf8ckpw3DadOZ2bo4YyeoAv6OJgp8JGYdw0C3UISfKpoiECdjJvuClk9ZFu5/i+J+3pTaedUbaxU+ps5hDfH5ubaRGLIro61Iz2bUfwqHftc5sxKhdfoEV1TI72gTs041I5I4=
