version: '3'
volumes:
  dbbackups:
  postgis-data:

services:
  mysqldb_retriever:
    image: mysql:5.7
    container_name: mysqldb_ret_container
    environment:
      MYSQL_USER: travis
      MYSQL_PASSWORD: Password12!
      MYSQL_ROOT_PASSWORD: Password12!
      MYSQL_DATABASE: testdb_retriever
    restart: on-failure
    healthcheck:
      test: "exit 0"
  pgdb_retriever:
    image: kartoza/postgis:latest
    volumes:
      - postgis-data:/var/lib/postgresql
      - dbbackups:/backups
    container_name: pgdb_ret_container
    environment:
      # To create multiple database you can add coma separated databases eg gis,data
      - POSTGRES_DB=testdb_retriever
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=Password12!
      - ALLOW_IP_RANGE=0.0.0.0/0
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster,pgrouting
    ports:
      - 25432:5432
    restart: on-failure
    healthcheck:
      test: "exit 0"
  python_retriever:
    container_name: ret_container
    image: ret_image
    command: bash -c "python --version"
    environment:
      # Handle tzdata install see: https://serverfault.com/a/975084
      TZ: America/New_York
      DEBIAN_FRONTEND: noninteractive
      # If IN_DOCKER is set, use service names as hosts(travis)
      # Otherwise use localhost (local tests)
      "IN_DOCKER" : "true"
      "PGUSER" : "postgres"
      "PGPASSWORD" : "Password12!"
      "PGDATABASE" : "testdb_retriever"
      "PGPORT" : "5432"
      "PGHOST" : "pgdb_retriever"
    restart: on-failure
    build: ./docker
    depends_on:
      mysqldb_retriever:
        condition: service_healthy
      pgdb_retriever:
        condition: service_healthy
    ports:
      - 5001:80
